<?php
/**
 * @file Integration with Moxtra JS SDK
 */

/**
 * Implements hook_menu().
 */
function dragon_moxtra_menu() {
  $items['chat'] = array(
    'page callback' => 'dragon_moxtra_chat_page',
    'access callback' => "user_is_logged_in",
  );

  $items['chat/add'] = array(
    'title' => 'Create New Binder',
    'page callback' => 'dragon_moxtra_binder_add_page',
    'access arguments' => array("create moxtra binder"),
  );
  return $items;
}

function dragon_moxtra_permission() {
  return array(
    'create moxtra binder' => array(
      'title' => t('Create moxtra binder'),
      'description' => t('Create moxtra binder'),
    ),
  );
}

function dragon_moxtra_cron() {
  return;
  // Try to find out all the messages for all the users
  module_load_include('inc', 'dragon_moxtra', 'dragon_moxtra.functions');
  $users = entity_load('user');
  
  foreach ($users as $uid => $user) {
    if($user->mail != null){
      watchdog('qad_test', 'mmm %data ms', array('%data' => print_r($user, TRUE)), WATCHDOG_ERROR);
      $response = dragon_moxtra_get_user_timeline($user);
      
      watchdog('qad_test', 'mmmm %data ms', array('%data' => print_r($response, TRUE)), WATCHDOG_ERROR);
      //break;
    }
  }
}

/**
 * Implements page callback for chat
 */
function dragon_moxtra_chat_page() {
  if (!user_is_logged_in()) {
    drupal_set_message(t('To get online live support, please login or register first.'), 'warning');
    drupal_goto("user");
  }
  
  module_load_include('inc', 'dragon_moxtra', 'dragon_moxtra.config');
  module_load_include('inc', 'dragon_moxtra', 'dragon_moxtra.functions');
  drupal_add_js('https://www.moxtra.com/api/js/moxtra-latest.js', 'external');

  global $CLIENT_ID, $REST_API_END_POINT;
  global $user;
  $user = user_load($user->uid);
  $access_token = dragon_moxtra_get_access_token();
  $site_mail = variable_get('site_mail');
  $lang = field_language('user', $user, 'field_company');
  $binder_name = !empty($user->field_company[$lang][0]['value']) ? 
    $user->field_company[$lang][0]['value'] : '';
  $binder_name = empty($binder_name) ? $user->name : $binder_name;
  drupal_add_js(
    array(
      'dragon_moxtra' =>
        array(
          'client_id' => $CLIENT_ID,
          'access_token' => $access_token,
          'rest_api_end_point' => $REST_API_END_POINT,
          'default_contact' => variable_get('dragon_moxtra_default_contact_mail', $site_mail),
          'binder_name' => $binder_name,
          'create_access' => user_access('create moxtra binder'),
      ),
    ),
    'setting'
  );
  drupal_add_js(drupal_get_path('module', 'dragon_moxtra') . '/js/dragon_moxtra.js');
  return '<div id="timeline_container"></div>';
}

function dragon_moxtra_binder_add_page() {
  $form = drupal_get_form('dragon_moxtra_binder_create_form');
  return $form;
}

function dragon_moxtra_binder_create_form($form, &$form_state) {
  global $user;

  $form['name'] = array(
    '#title' => t('Binder Name'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );

  $accounts = entity_load('user');
  foreach ($accounts as $account) {
    if ($account->status == TRUE && $account->uid != $user->uid) {
      $user_options[$account->mail] = $account->name . ' <' . $account->mail . '>';
    }
  }
  $form['accounts'] = array(
    '#title' => t('Users'),
    '#type' => 'select',
    '#multiple' => 'multiple',
    '#options' => $user_options,
    '#size' => min(10, count($user_options)),
    '#description' => t('Select the users to join the binder. You will be included in the binder by default.'),
  );
  
  $form['emails'] = array(
    '#title' => t('Addtional email addresses'),
    '#type' => 'textfield',
    '#description' => t('Put the email addresses for users haven\'t registered for our site. Use comma to separate.'),
  );
  
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

  $form['#attached']['css'] = array(
    drupal_get_path('module', 'dragon_moxtra') . '/css/bootstrap-multiselect.css',
    drupal_get_path('module', 'dragon_moxtra') . '/css/dragon_moxtra_multiselect.css',
  );
  $form['#attached']['js'] = array(
    drupal_get_path('module', 'dragon_moxtra') . '/js/bootstrap-multiselect.js',
    drupal_get_path('module', 'dragon_moxtra') . '/js/dragon_moxtra_multiselect.js',
  );

  return $form;
}

function dragon_moxtra_binder_create_form_submit($form, &$form_state) {
  module_load_include('inc', 'dragon_moxtra', 'dragon_moxtra.config');
  module_load_include('inc', 'dragon_moxtra', 'dragon_moxtra.functions');
  $name = $form_state['values']['name'];
  $accounts = $form_state['values']['accounts'];
  $mail_list = $form_state['values']['emails'];
  
  // Create the users
  if($mail_list != null){
    $mails = explode(',', $mail_list);
    foreach ($mails as $mail) {
      if(!user_load_by_mail($mail)){
        dragon_moxtra_create_user_by_mail($mail);
      }
      $accounts[] = $mail;
    }
  }
  
  $members = array();
  foreach ($accounts as $account) {
    // Check if this users has been created in Moxtra
    dragon_moxtra_get_access_token(true, user_load_by_mail($account));
    $members[] = array(
      'user' => array(
        'unique_id' => $account,
      ),
    );
  }
  
  $response = dragon_moxtra_create_binder($name, $members);

  $form_state['redirect'] = 'chat';
}


function dragon_moxtra_create_user_by_mail($mail) {
  // This will generate a random password, you could set your own here
  $password = user_password(8);
 
  // Set up the user fields
  $fields = array(
    'name' => $mail,
    'mail' => $mail,
    'pass' => $password,
    'status' => 1,
    'init' => 'email address',
    'roles' => array(
      DRUPAL_AUTHENTICATED_RID => 'authenticated user',
    ),
  );
 
  //the first parameter is left blank so a new user is created
  $account = user_save('', $fields);
}
