<?php
  global $CLIENT_ID, $CLIENT_SECRET, $REST_API_END_POINT, $OAUTH_ENDPOINT_DOMAIN, $SDK_MODE, $USER_INITIALIZE_GRANT_TYPE;
  // Partner account
  $CLIENT_ID = "pNvbm-FN460";
  $CLIENT_SECRET = "sR7CVSKn2Tc";

  $REST_API_END_POINT = "https://apisandbox.moxtra.com/v1"; //For production use "https://api.moxtra.com"
  $OAUTH_ENDPOINT_DOMAIN = "https://apisandbox.moxtra.com"; //For production use "https://api.moxtra.com"
  $SDK_MODE = "sandbox"; //For production use "production"
  $USER_INITIALIZE_GRANT_TYPE = "http://www.moxtra.com/auth_uniqueid";
