<?php

function dragon_project_menu() {
  $items['quote'] = array(
    'title' => 'Get A QUOTE',
    'page callback' => 'dragon_project_create',
    'access callback' => 'node_access',
    'access arguments' => array('create', 'project'),
    'file' => 'node.pages.inc',
    'file path' => drupal_get_path('module', 'node'),
  );
  return $items;
}

function dragon_project_create() {
  global $user;
  $node = (object) array('uid' => $user->uid, 'name' => (isset($user->name) ? $user->name : ''), 'type' => 'project', 'language' => LANGUAGE_NONE);
  $output = drupal_get_form('project' . '_node_form', $node);

  return $output;
}

/*
 * Implements hook_preprocess_page
 */
function dragon_project_preprocess_page(&$vars, $hook) {
  if(arg(0) == 'quote') {
    drupal_add_css(drupal_get_path('module', 'dragon_project') . '/css/dragon_project_create.css');
  }
}

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function dragon_project_block_info() {
  $blocks['dragon_quote'] = array(
    'info' => t('Dragon Get Quote'),
    'region' => 'content',
    'status' => TRUE
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function dragon_project_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  if ($delta == 'dragon_quote') {
    $block['subject'] = NULL;
    $block['content'] = _dragon_project_quote_block();
    $block['#attached'] = array(
      'css' => array(
        drupal_get_path('module', 'dragon_project') . '/css/dragon_project_quote_block.css',
      )
    );
  }
  return $block;
}

function _dragon_project_quote_block(){
  drupal_add_css(drupal_get_path('module', 'dragon_project') . '/css/dragon_project_quote_block.css');
  return array(
    'text' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array('dragon-quote-text'),
      ),
      array(
        '#type' => 'markup',
        '#markup' => 'Get a Quote',
      ),
    ),
    'content' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array('dragon-quote-content'),
      ),
      array(
        '#type' => 'markup',
        '#markup' => 'Some description',
      ),
    ),
    'link' => array(
      '#type' => 'link',
      '#attributes' => array(
        'class' => array('dragon-quote-link'),
      ),
      '#title' => 'Start Now',
      '#href' => 'quote',
    ),
  );
}
