<?php

function dragon_project_menu() {
  $items['quote'] = array(
    'title' => 'Get A QUOTE',
    'page callback' => 'dragon_project_create_page_inteface',
    'access callback' => 'node_access',
    'access arguments' => array('create', 'project'),
    'file' => 'node.pages.inc',
    'file path' => drupal_get_path('module', 'node'),
  );
  return $items;
}

function dragon_project_create_page_inteface() {
  module_load_include('inc', 'dragon_project', 'dragon_project.pages');
  return dragon_project_create_page();
}

/*
 * Implements hook_preprocess_page
 */
function dragon_project_preprocess_page(&$vars, $hook) {
  if(arg(0) == 'quote') {
    drupal_add_css(drupal_get_path('module', 'dragon_project') . '/css/dragon_project_create.css');
  }
}

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function dragon_project_block_info() {
  $blocks['dragon_quote'] = array(
    'info' => t('Dragon Get Quote'),
    'region' => 'content',
    'status' => TRUE
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function dragon_project_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  if ($delta == 'dragon_quote') {
    module_load_include('inc', 'dragon_project', 'dragon_project.pages');
    
    $block['subject'] = NULL;
    $block['content'] = _dragon_project_quote_block();
  }
  return $block;
}

function dragon_project_field_group_pre_render_alter(&$element, $group, & $form) {
  $element['#attributes']['id'] = $group->group_name;
}