<?php
/**
 * @file
 */

/**
 * Implements hook_block_info().
 */
function dragon_footer_block_info() {
  $blocks['dragon_footer_about'] = array(
    'info' => t('Dragon Footer - About'),
    'status' => TRUE,
    'region' => 'footer_first',
    'cache' => DRUPAL_CACHE_PER_ROLE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
  );

  $blocks['dragon_footer_follow'] = array(
    'info' => t('Dragon Footer - Follow'),
    'status' => TRUE,
    'region' => 'footer_second',
    'cache' => DRUPAL_CACHE_PER_ROLE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
  );

  $blocks['dragon_footer_download'] = array(
    'info' => t('Dragon Footer - Download'),
    'status' => TRUE,
    'region' => 'footer_third',
    'cache' => DRUPAL_CACHE_PER_ROLE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
  );

  $blocks['dragon_footer_help'] = array(
    'info' => t('Dragon Footer - Help'),
    'status' => TRUE,
    'region' => 'footer_fourth',
    'cache' => DRUPAL_CACHE_PER_ROLE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
  );

  $blocks['dragon_footer_bottom'] = array(
    'info' => t('Dragon Footer - Bottom'),
    'status' => TRUE,
    'region' => 'footer',
    'cache' => DRUPAL_CACHE_PER_ROLE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dragon_footer_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'dragon_footer_about':
      $block['subject'] = t('');
      $block['content'] = _dragon_footer_about_html();
      break;
    case 'dragon_footer_follow':
      $block['subject'] = t('');
      $block['content'] = _dragon_footer_follow_html();
      break;
    case 'dragon_footer_download':
      $block['subject'] = t('');
      $block['content'] = _dragon_footer_download_html();
      break;
    case 'dragon_footer_help':
      $block['subject'] = t('');
      $block['content'] = _dragon_footer_help_html();
      break;
    case 'dragon_footer_bottom':
      $block['subject'] = t('');
      $block['content'] = _dragon_footer_bottom_html();
      break;
  }

  return $block;
}

/**
 * Implements _dragon_footer_markup()
 */
function _dragon_footer_about_html() {
  return array(
    'block' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array('dragon-footer-about'),
      ),
      'title' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('dragon-footer-title'),
        ),
        'html' => array(
          '#type' => 'markup',
          '#markup' => t('About Dragon Asia'),
        ),
      ),
      'content' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('dragon-footer-content'),
        ),
        'html' => array(
          '#type' => 'markup',
          '#markup' => t('About Dragon Asia is a company.....
          About Dragon Asia is a company.....About Dragon Asia is a company.....
          About Dragon Asia is a company.....'),
        ),
      ),
    ),
  );
}

/**
 * Implements _dragon_footer_markup()
 */
function _dragon_footer_follow_html() {
  return array(
    'block' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array('dragon-footer-follow'),
      ),
      'title' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('dragon-footer-title'),
        ),
        'html' => array(
          '#type' => 'markup',
          '#markup' => t('Follow Us'),
        ),
      ),
      'content' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('dragon-footer-content'),
        ),
        'linkedin' => array(
          '#type' => 'container',
          '#attributes' => array(
            'class' => array('dragon-footer-icon'),
          ),
          'html' => array(
            '#type' => 'markup',
            '#markup' => t('in'),
          ),
        ),
      ),
    ),
  );
}

/**
 * Implements _dragon_footer_markup()
 */
function _dragon_footer_download_html() {
  return array(
    'block' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array('dragon-footer-about'),
      ),
      'title' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('dragon-footer-title'),
        ),
        'html' => array(
          '#type' => 'markup',
          '#markup' => t('Downloads'),
        ),
      ),
      'content' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('dragon-footer-content'),
        ),
        'list' => array(
          '#theme' => 'item_list',
          '#type' => 'ul',
          '#items' => array(
            dragon_common_gen_icon_link('File A.pdf', '', 'glyphicon-file', NULL),
          ), 
          '#attributes' => array(
            'class' => array('list-unstyled'),
          ),
        ),
      ),
    ),
  );
}

/**
 * Implements _dragon_footer_markup()
 */
function _dragon_footer_help_html() {
  return array(
    'block' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array('dragon-footer-about'),
      ),
      'title' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('dragon-footer-title'),
        ),
        'html' => array(
          '#type' => 'markup',
          '#markup' => t('Help'),
        ),
      ),
      'content' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('dragon-footer-content'),
        ),
        'list' => array(
          '#theme' => 'item_list',
          '#type' => 'ul',
          '#items' => array(
            dragon_common_gen_icon_link('Get a quote', '', 'glyphicon-pencil', NULL),
            dragon_common_gen_icon_link('Live Chat', '', 'glyphicon-user', NULL),
          ), 
          '#attributes' => array(
            'class' => array('list-unstyled'),
          ),
        ),
      ),
    ),
  );
}

/**
 * Implements _dragon_footer_markup()
 */
function _dragon_footer_bottom_html() {
  return array(
    'block' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array('dragon-footer-bottom'),
      ),
      'links' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('dragon-footer-links dragon-footer-content'),
        ),
        array(
          '#type' => 'markup',
          '#markup' => l('Sitemap', 'sitemap') . ' | ' . l('Disclaimer', 'disclaimer') . ' | ' . t('© 2015 Dragon Asia. All Rights Reserved.'),
        ),
      ),
    ),
  );
}

function _qad_footer_block_add_icon($image_path, $link_path, $tag_a_attr = NULL, $tag_img_attr = NULL) {
  //Build the icon
  $icon = array(
    'path' => $image_path,
    'attributes' => $tag_img_attr,
  );

  //Wrapped with the image theme
  $wrapped_icon = theme('image', $icon);

  // Tell Drupal that the text is html
  $options['html'] = TRUE;
  $options['attributes'] = $tag_a_attr;

  return l($wrapped_icon, $link_path, $options);
}
