<?php

function dragon_menu_menu() {

  $items['quote'] = array(
    'title' => 'Get A QUOTE',
    'page callback' => 'dragon_menu_quote_form',
  );

  $node_info = _dragon_menu_node_info();
  foreach ($node_info as $node_path => $node_title) {
    $node_key = str_replace('-', '_', $node_path);
    $node_nid = variable_get('dragon_menu_node_' . $node_key);
    $node = node_load($node_nid);
    $items[$node_path] = array(
      'title' => $node_title,
      'page callback' => 'dragon_menu_node_page_view',
      'page arguments' => array($node),
      'access callback' => 'node_access',
      'access arguments' => array('view', $node),
    );
  }
  return $items;
}

function dragon_menu_node_page_view($node) {
  $markup = node_view($node, 'full');

  //print_r($markup);
  return $markup['body'];
}

/**
 * Help function to store the node info for use
 * @return multitype:string
 */
function _dragon_menu_node_info() {
  $node_info = array(
    'careers' => 'Careers',
    'support' => 'Support',
    'contact' => 'Contact',
    'about-us' => 'About Us',
    'industry' => 'Industry',
    'sport-accessories' => 'Sport Accessories',
    'home-textile' => 'Home Textile',
  );

  return $node_info;
}
