<?php

function dragon_menu_menu() {

  $items['quote'] = array(
    'title' => 'Get A QUOTE',
    'page callback' => 'dragon_menu_quote_form',
  );

  $node_info = _dragon_menu_node_info();
  foreach ($node_info as $node_path => $node_title) {
    $node_key = str_replace('-', '_', $node_path);
    $node_nid = variable_get('dragon_menu_node_' . $node_key);
    $node = node_load($node_nid);
    $items[$node_path] = array(
      'title' => $node_title,
      'page callback' => 'dragon_menu_node_page_view',
      'page arguments' => array($node),
      'access callback' => 'node_access',
      'access arguments' => array('view', $node),
    );
  }
  return $items;
}

function dragon_menu_node_page_view($node) {
  $markup = node_view($node, 'full');

  //print_r($markup);
  return $markup['body'];
}

/**
 * Help function to store the node info for use
 * @return multitype:string
 */
function _dragon_menu_node_info() {
  $node_info = array(
    'careers' => 'Careers',
    'support' => 'Support',
    'contact' => 'Contact',
    'about-us' => 'About Us',
    'industry' => 'Industry',
    'sport-accessories' => 'Sport Accessories',
    'home-textile' => 'Home Textile',
  );

  return $node_info;
}
/**
* Implements hook_block_info().
*/
function dragon_menu_block_info() {
  $blocks = array();
  $blocks = array(
    'logo' => array(
      'info' => t('Site logo and name'),
    ),
  );
  return $blocks;
}
/**
* Implements hook_block_view().
*/
function dragon_menu_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'logo':
      $block['subject'] = '';
      $block['content'] = _dragon_menu_logo_name_block();
      break;
  }
  return $block;
}

function _dragon_menu_logo_name_block() {
  $html = array(
    '#type' => 'container',
    'logo' => array(
      '#type' => 'container',
      '#attributes' => array(
        'id' => 'dragon-site-logo'
      ),
      'content' => array(
        '#type'    => 'link',
        '#title'   => theme('image', array('path' => base_path()  .  path_to_theme() . '/logo.png')),
        '#href'    => '',
        '#options' => array('html' => TRUE),
        ''
      ),
    ),
    'name' => array(
      '#type' => 'container',
      '#attributes' => array(
        'id' => 'dragon-site-name'
      ),
      'content' => array(
        '#type'    => 'link',
        '#title'   => variable_get('site_name'),
        '#href'    => '',
        '#options' => array('html' => TRUE, 'title'),
      ),
    ),
    'slogan' => array(
      '#type' => 'container',
      '#attributes' => array(
        'id' => 'dragon-site-slogan'
      ),
      'content' => array(
        '#type'    => 'link',
        '#title'   => variable_get('site_slogan'),
        '#href'    => '',
        '#options' => array('html' => TRUE),
      ),
    ),
  );

/*
  $html .= '<img src="' .  base_path()  .  path_to_theme() . '/logo.png" width="150" height="150" alt="logo" />';
  $slogan = variable_get('site_slogan', 'null');
  $html .= '<p class="slogan">' .$slogan .'</p>';
*/
  return drupal_render($html);
}