<?php

/**
 * Implements hook_form_FORM_ID_alter()
 * Add a role selector in registiion
 */
function dragon_user_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  if (!user_access('administer users')) {
    $form['account']['role'] = array(
      '#type' => 'select',
      '#title' => t('Roles'),
      '#required' => TRUE,
      '#weight' => 2000,
      '#options' => array(
        user_role_load_by_name('customer')->rid => 'Customer',
        user_role_load_by_name('supplier')->rid => 'Supplier',
        user_role_load_by_name('forwarder')->rid => 'Forwarder',
        user_role_load_by_name('broker')->rid => 'Broker',
        user_role_load_by_name('employee')->rid => 'Employee',
      ),
      '#description' => t('Please select a role for you in this site.'),
    );
    $form['field_registered_capital']['#access'] = FALSE;
    //$form['field_years_in_registration']['#access'] = FALSE;
    array_unshift($form['#submit'], 'dragon_user_register_submit');
  }
}

/**
 * Customized submit handler for the user registration form.
 */
function dragon_user_register_submit($form, &$form_state) {
  $rid = $form_state['values']['role'];
  if ($rid == user_role_load_by_name('customer')->rid) {
    $form_state['values']['status'] = TRUE;
  }
  $form_state['values']['roles'][$rid] = TRUE;
}

/**
 * Implements hook_form_FORM_ID_alter()
 * Add a role selector in registiion
 */
function dragon_user_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'dragon_user_profile_submit';
  $account = $form['#user'];
  global $user;
  if (in_array('administrator', $user) && in_array('administrator', $account->roles)) {
    $form['field_registered_capital']['und']['#required'] = FALSE;
    $form['field_years_in_registration']['#access'] = false;
    $form['field_registered_capital']['#access'] = false;
    $form['field_industry']['#access'] = false;
  }
}

/**
 * Customized submit handler for the user profile form.
 */
function dragon_user_profile_submit($form, &$form_state) {
  $form_state['redirect'] = '' ;
}
